export const CHANGE_INPUT = "CHANGE_INPUT";

//auth action types

export const SIGNIN_SUCCESSFUL = 'SIGNIN_SUCCESSFUL';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGN_OUT = 'SIGN_OUT';

export const SIGNUP_SUCCESSFUL = 'SIGNUP_SUCCESSFUL';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const USER_LOADING = 'USER_LOADING';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const SET_STUDENT = 'SET_STUDENT';
export const SET_COMPANY = 'SET_COMPANY';

export const FETCH_COMPANY_SUCCESS = 'FETCH_COMPANY_SUCCESS';
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS';
export const SELECTED_PROFILE = 'SELECTED_PROFILE';
export const VACANCY_POSTED = 'VACANCY_POSTED'
